GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name" : "Jus Buah Naga",
    "type" : "Minuman"
}

###
GET http://localhost:3000/products/5ee88fdb5d4a2e6368308b8b

###
DELETE http://localhost:3000/products/5ef3487d7dd0fa65f457b4ac

###
PATCH http://localhost:3000/products/5ef349f01916e3622c77cb00
Content-Type: application/json

{
    "type" : "Minuman"
}

